### ISSUE TITLE
Clarificaitons could be useful

### ISSUE THREAD

**Issue by Fahrenheit2539** [almerico/bombardier#7]
* Does it requires large bandwidth (does not seem like it), or it just spams with connections?
* Does it make sense to run from multiple machines in a single network? The more the merrier? :)

**Comment by AnthonyKot** [comment]
I may share my experience. Overall it looks quite efficient on medium grade notebook. Both CPU and bandwidth (25Mbps) are consumed completely

**Comment by nideKer** [comment]
How to check outgoing logs or some stats?

**Comment by SankaranarayananA** [comment]
> How to check outgoing logs or some stats?

If you are using docker desktop , you can easily view it in container tab.
or otherwise use command
 docker logs [OPTIONS] CONTAINER

**Comment by SankaranarayananA** [comment]
> * Does it requires large bandwidth (does not seem like it), or it just spams with connections?
> * Does it make sense to run from multiple machines in a single network? The more the merrier? :)

By reviewing this repository,  I can say the code is consuming more bandwidth while the DDOS attacks are not doing much better than your usual browser  requests. If you are preferring for much better solutions , search for slow Loris or safyra in GitHub.

**Comment by Ivan9307** [comment]
PS C:\Users\Ivan> docker run -d --rm alpine/bombardier -c 1000 -d 60000h -l http://kremlin.ru
Unable to find image 'alpine/bombardier:latest' locally
latest: Pulling from alpine/bombardier
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.

що я роблю не так?

**Comment by Fahrenheit2539** [comment]
I'd suggest to join https://t.me/itarmyofukraine2022 for more up-to-date information, targeting and tooling.
